{% set name = "O365" %}
{% set version = "2.0.36" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/O365-{{ version }}.tar.gz
  sha256: 85403b6270169c31e572e63dff1daa38be62d030dac01ada428908c0214928b6

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.9
    - wheel
    - pip
  run:
    - python >=3.9
    - requests >=2.31.0
    - requests-oauthlib >=1.2.0
    - python-dateutil >=2.7
    - tzlocal >=5.0
    - beautifulsoup4 >=4.0.0
    - stringcase >=1.2.0
    - python-tzdata >=2023.4

test:
  imports:
    - O365
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/O365/python-o365
  summary: Microsoft Graph and Office 365 API made easy
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - owenlamont
