{% set name = "O365" %}
{% set version = "2.0.34" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/O365-{{ version }}.tar.gz
  sha256: 1c28c9bfb59d0da498ba80e7682301af61414e922fb46740894bb6c9bc8d99c8

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.9
    - wheel
    - pip
  run:
    - python >=3.9
    - requests >=2.18.0
    - requests-oauthlib >=1.2.0
    - python-dateutil >=2.7
    - tzlocal >=5.0
    - beautifulsoup4 >=4.0.0
    - stringcase >=1.2.0

test:
  imports:
    - O365
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/O365/python-o365
  summary: Microsoft Graph and Office 365 API made easy
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - owenlamont
