{% set name = "O365" %}
{% set version = "2.0.31" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/O365-{{ version }}.tar.gz
  sha256: 05b367a58e47cc536f58a9bbf25a1a10083a9be3c5d2fd7efc45c9ad015b87d0

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - wheel
    - pip
  run:
    - python >=3.7
    - requests >=2.18.0
    - requests-oauthlib >=1.2.0
    - python-dateutil >=2.7
    - pytz >=2018.5
    - tzlocal >=4.0,<5.0
    - beautifulsoup4 >=4.0.0
    - stringcase >=1.2.0

test:
  imports:
    - O365
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/O365/python-o365
  summary: Microsoft Graph and Office 365 API made easy
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - owenlamont
