{% set name = "O365" %}
{% set version = "2.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | lower }}-{{ version }}.tar.gz
  sha256: eebb4f78b8920fd86770b54f40f4d489e0b0d154ffbce883464ecc40ce23b69d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - wheel
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - requests >=2.32.0
    - requests-oauthlib >=2.0.0
    - python-dateutil >=2.7
    - tzlocal >=5.0
    - beautifulsoup4 >=4.0.0
    - python-tzdata >=2023.4

test:
  imports:
    - O365
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/O365/python-o365
  summary: Microsoft Graph and Office 365 API made easy
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - owenlamont
